/cloud/app_id: 'Paste your App ID here'
/cloud/app_token: 'Paste your App Token here'
/cloud/location_id: 'Paste your Location identifier here'
/cloud/url: 'https://cloud.estimote.com'
/port/serial_port: '/dev/ttyUSB0'
/beacons/panid: 'Paste the PanID value displayed in the Estimote Indoor app after enabling the robotics mode'
# The recommended beacon placement height is 2.1 meter. 
# Change this value if for some reason you have to place them higher or lower.
/beacons/placement_height: 2.1
# indoor | outdoor | mixed - choose the one that describes your scenario.
/beacons/environment: 'indoor'